version: "3"

services:
  frontend:
    image: webpack
    build:
      context: ./app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app:rw
      - node_modules:/src/node_modules
    command: npm run start:production
volumes:
  node_modules: